---
- hosts: ubuntu
  tasks:
    - name: Execute Shell Commands
      shell: uname
      register: uname_result

    - debug: msg="{{ uname_result.stdout }}"---
- hosts: ubuntu
  tasks:
    - name: Execute Shell Commands
      shell: uname
      register: uname_result

    - debug: msg="{{ uname_result.stdout }}"
